### ISSUE TITLE
artifact of delusion compatibility

### ISSUE THREAD

**Issue by frozenden14564886954** [SSM240/FadeEmptyChests#1]
when using the new artifact of delusion in the devotion update, it would be nice for opened chests to unfade after the teleporter event, or simply to never fade if the artifact is active.

it is still possible to interact with the chests while they are faded out unlike other mods that will remove them entirely, but now the mod is working too well and they are harder to find lol

ty for this mod <3

**Comment by SSM240** [comment]
Yeah I've been meaning to take a look at that for a while, will try to remember to when I get the chance. Feel free to poke me if I don't have it done in a couple days. Thanks for the report.

**Comment by SSM240** [comment]
Should now be fixed in v1.1.1.
